# Generated by Django 5.2.2 on 2025-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
