# Generated by Django 5.2.2 on 2025-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_role',
            field=models.CharField(blank=True, default='staff', max_length=255, null=True),
        ),
    ]
