# Generated by Django 5.2.2 on 2025-06-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_domain_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_use_ssl',
            field=models.BooleanField(default=True),
        ),
    ]
