# Generated by Django 5.2.2 on 2025-07-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenantconfig_email_templates_alter_tenantconfig_logo'),
        ('core', '0005_initialize_tenant_configs'),
    ]

    operations = [
    ]
