# Generated by Django 5.2.2 on 2025-06-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_domain_tenant'),
        ('job_application', '0001_initial'),
        ('talent_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='talent_engine.jobrequisition'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('tenant', 'job_requisition', 'email')},
        ),
    ]
