# Generated by Django 5.2.2 on 2025-06-30 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_tenant_default_from_email_tenant_email_host_and_more'),
        ('job_application', '0001_initial'),
        ('talent_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='talent_engine.jobrequisition'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='job_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='job_application.jobapplication'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('tenant', 'job_requisition', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('tenant', 'job_application', 'interview_date_time')},
        ),
    ]
