# Generated by Django 5.2.2 on 2025-07-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('job_application', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('tenant', 'job_application', 'interview_start_date_time', 'branch')},
        ),
    ]
