# Generated by Django 5.2.2 on 2025-06-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
