# Generated by Django 5.2.2 on 2025-07-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_alter_jobapplication_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='employment_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
