# Generated by Django 5.2.2 on 2025-06-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_domain_tenant'),
        ('job_application', '0003_jobapplication_screening_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('interview_date_time', models.DateTimeField()),
                ('meeting_mode', models.CharField(choices=[('Virtual', 'Virtual'), ('Physical', 'Physical')], max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=255, null=True)),
                ('interview_address', models.TextField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='job_application.jobapplication')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.tenant')),
            ],
            options={
                'db_table': 'job_applications_schedule',
                'unique_together': {('tenant', 'job_application', 'interview_date_time')},
            },
        ),
    ]
