# Generated by Django 5.2.2 on 2025-07-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_jobapplication_employment_gaps'),
    ]

    operations = [
    ]
