# Generated by Django 5.2.2 on 2025-06-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_schedule_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
