# Generated by Django 5.2.2 on 2025-07-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_auto_20250707_1114'),
    ]

    operations = [
    ]
