# Generated by Django 5.2.2 on 2025-06-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0006_jobapplication_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
