# Generated by Django 5.2.2 on 2025-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0006_auto_20250707_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='compliance_status',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
