# Generated by Django 5.2.2 on 2025-07-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0007_jobapplication_compliance_status'),
    ]

    operations = [
    ]
