# Generated by Django 5.2.2 on 2025-06-26 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0008_alter_jobapplication_id_alter_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
    ]
