# Generated by Django 5.2.2 on 2025-07-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0008_auto_20250708_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time (US)'), ('America/Chicago', 'Central Time (US)'), ('America/Los_Angeles', 'Pacific Time (US)'), ('Europe/London', 'London'), ('Asia/Tokyo', 'Tokyo')], default='UTC', max_length=100),
        ),
    ]
