# Generated by Django 5.2.2 on 2025-07-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rolepermission_role_branch'),
        ('job_application', '0009_schedule_timezone'),
        ('talent_engine', '0007_jobrequisition_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='core.branch'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('tenant', 'job_requisition', 'email', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('tenant', 'job_application', 'interview_date_time', 'branch')},
        ),
    ]
