# Generated by Django 5.2.2 on 2025-06-26 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0009_alter_schedule_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
    ]
