# Generated by Django 5.2.2 on 2025-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('job_requisition_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('job_application_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('num_of_applications', models.IntegerField(default=0, help_text='Number of successful (hired) applications')),
                ('title', models.CharField(max_length=255)),
                ('unique_link', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='rejected', max_length=20)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], default='staff', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('location_type', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=20)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('job_location', models.TextField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('number_of_candidates', models.IntegerField(blank=True, null=True)),
                ('qualification_requirement', models.TextField(blank=True, null=True)),
                ('experience_requirement', models.TextField(blank=True, null=True)),
                ('knowledge_requirement', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('documents_required', models.JSONField(blank=True, default=list)),
                ('compliance_checklist', models.JSONField(blank=True, default=list)),
                ('advert_banner', models.ImageField(blank=True, null=True, upload_to='advert_banners/')),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('publish_status', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'talent_engine_job_requisition',
            },
        ),
    ]
