# Generated by Django 5.2.2 on 2025-06-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
