# Generated by Django 5.2.2 on 2025-06-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
