# Generated by Django 5.2.2 on 2025-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0002_jobrequisition_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='job_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
