# Generated by Django 5.2.2 on 2025-06-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0002_alter_jobrequisition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='advert_banner',
            field=models.ImageField(blank=True, null=True, upload_to='advert_banners/'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='compliance_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='documents_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='location_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=20),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='number_of_candidates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='experience_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='knowledge_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='qualification_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
