# Generated by Django 5.2.2 on 2025-07-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0002_initial'),
    ]

    operations = [
    ]
