# Generated by Django 5.2.2 on 2025-06-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0003_jobrequisition_advert_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='publish_status',
            field=models.BooleanField(default=False),
        ),
    ]
