# Generated by Django 5.2.2 on 2025-07-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0003_auto_20250706_2252'),
    ]

    operations = [
    ]
