# Generated by Django 5.2.2 on 2025-07-31 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_logo_tenant_title'),
        ('talent_engine', '0003_videosession_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='meeting_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='videosession',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videosession',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='core.tenant'),
            preserve_default=False,
        ),
    ]
