# Generated by Django 5.2.2 on 2025-06-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0003_jobrequisition_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
