# Generated by Django 5.2.2 on 2025-06-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0004_jobrequisition_publish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='job_role',
            field=models.CharField(blank=True, default='staff', max_length=255, null=True),
        ),
    ]
