# Generated by Django 5.2.2 on 2025-07-07 10:31

import talent_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0004_auto_20250707_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='checked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='last_compliance_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='compliance_checklist',
            field=models.JSONField(blank=True, default=list, validators=[talent_engine.models.validate_compliance_checklist]),
        ),
    ]
