# Generated by Django 5.2.2 on 2025-07-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0005_jobrequisition_checked_by_and_more'),
    ]

    operations = [
    ]
