# Generated by Django 5.2.2 on 2025-06-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0005_jobrequisition_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequisition',
            name='job_role',
        ),
    ]
