# Generated by Django 5.2.2 on 2025-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_engine', '0006_remove_jobrequisition_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='rejected', max_length=20),
        ),
    ]
