# Generated by Django 5.2.2 on 2025-07-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rolepermission_role_branch'),
        ('talent_engine', '0006_auto_20250708_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
